<?php
/**
 * @file
 * wysiwyg_advanced_profile.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function wysiwyg_advanced_profile_filter_default_formats() {
  $formats = array();

  // Exported format: Advanced HTML.
  $formats['advanced_html'] = array(
    'format' => 'advanced_html',
    'name' => 'Advanced HTML',
    'cache' => 1,
    'status' => 1,
    'weight' => 0,
    'filters' => array(
      'filter_url' => array(
        'weight' => -48,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_autop' => array(
        'weight' => -47,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_htmlcorrector' => array(
        'weight' => -46,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
